---
- name: Java

  hosts: prepared_machines

  vars_files:
    - vars/secure_vars.yml
    - vars/java_vars.yml

  tasks:
    - name: Install JDK
      unarchive:
        src: https://s3.eu-central-1.amazonaws.com/ansible.repo/{{ java_version }}.tar.gz
        dest: /
        copy: no
        owner: '{{ user }}'
        group: '{{ user }}'
        creates: /opt/{{ java_version }}

    - name: Set JAVA_HOME
      lineinfile:
        dest: /etc/environment
        regexp: ^JAVA_HOME
        line: JAVA_HOME=/opt/{{ java_version }}
