---
- name: Prepare new machine

  hosts: new_machines

  vars_files:
    - vars/secure_vars.yml
    - vars/java_vars.yml

  tasks:
    - include: tasks_security.yml
    - include: tasks_letsencrypt.yml
    - include: tasks_java.yml
    - include: tasks_postgres.yml
    - include: tasks_teamcity.yml
    - include: tasks_nexus.yml
    - include: tasks_sonar.yml
