---
- name: Prepare new machine

  hosts: new_machines

  vars_files:
    - vars/secure_vars.yml
    - vars/java_vars.yml

  tasks:
    - include: tasks_security.yml
    - include: tasks_java.yml
    - include: tasks_postgres.yml
    - include: tasks_teamcity.yml

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
